<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.10.2"/>
    <PackageReference Include="OpenCCNET" Version="1.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLIT.Utils\BLIT.Utils.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="gsdll64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

